name: Terraform workflow

on: workflow_dispatch

env:
  AWS_REGION:  us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04

    steps:
      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.3"

      - name: Initialize terraform
        run: |
          terraform init \
          -backend-config="bucket=${{ secrets.TF_S3_BACKEND_BUCKET_NAME }}" \
          -backend-config="key=${{ secrets.TF_S3_BACKEND_KEY }}" \
          -backend-config="dynamodb_table=${{ secrets.TF_S3_BACKEND_DYNAMODB_TABLE }}" \
          -backend-config="assume_role={role_arn=\"${{ secrets.TF_S3_BACKEND_ROLE_ARN }}\"}"

      - name: Terraform plan
        run: |
          terraform plan -out terraform-plan.binary
          terraform show -json terraform-plan.binary > terraform-plan.json

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.0.0

      - name: Run OPA Tests
        run: |
          opa_output=$(opa eval --data ${{ github.workspace }}/policies/allowed_ec2_instance_types.rego --input=${{ github.workspace }}/terraform-plan.json | jq -r '.result[].expressions[].value[]')
          [ -z "$opaout" ] && exit 0 || echo "$opaout" && gh pr comment ${{ github.event.pull_request.number }} --body "### $opaout" && exit 1

      - name: List state file resources
        run: terraform state list